### ISSUE TITLE
Bug maven

### ISSUE THREAD

**Issue by BeanGTA** [PetteriM1/Nukkit-SuomiCraftPE#18]
https://i.loli.net/2018/10/09/5bbcaa4469f33.png

Help me

**Comment by PetteriM1** [comment]
Hmm git commit id plugin fails... Does it work if you compile it outside NetBeans IDE?

**Comment by BeanGTA** [comment]
Thank rep, I changed it, I moved 2.2.1 to 2.1.13 and it worked great

**Comment by PetteriM1** [comment]
Ok good

**Comment by BeanGTA** [comment]
Hey When I joined the game, it stopped

https://i.loli.net/2018/10/09/5bbcb15f21052.png
https://i.loli.net/2018/10/09/5bbcb160d0d66.png
https://i.loli.net/2018/10/09/5bbcb1611bff1.png
https://i.loli.net/2018/10/09/5bbcb1614f93a.png

**Comment by PetteriM1** [comment]
Thats because of plugins that can't work in my Nukkit. For skyblock you need to change biome code to old format or use my skyblock fork. Mob plugin is not needed and can't work because I have mob AI and autospawning implemented to Nukkit. So its not even needed.

**Comment by BeanGTA** [comment]
That's great for me to try

**Comment by BeanGTA** [comment]
Bug SkyBlock water killer lava =((
