### ISSUE TITLE
jansi wont load arm64

### ISSUE THREAD

**Issue by BeanGTA** [PetteriM1/Nukkit-SuomiCraftPE#19]
https://i.loli.net/2018/10/15/5bc37a1eb3d68.png

Ok...I run it in the old version without errors, this new version is faulty

**Comment by PetteriM1** [comment]
test this [https://drive.google.com/open?id=1Q4OGR_WYyGq2Je_7Rsy14Gb3xN9CY8wU](https://drive.google.com/open?id=1Q4OGR_WYyGq2Je_7Rsy14Gb3xN9CY8wU)

**Comment by BeanGTA** [comment]
Google link does not support .jar
https://i.loli.net/2018/10/15/5bc37d9ade45b.png

**Comment by PetteriM1** [comment]
you cant use web browser to download that?

**Comment by BeanGTA** [comment]
I use the web, and it stands still, what google usually warns .jar files is harmful

**Comment by PetteriM1** [comment]
Yeah google warns jar files harmful but you can still download them

**Comment by BeanGTA** [comment]
https://i.loli.net/2018/10/15/5bc37efb51e4d.png

It stood still

**Comment by BeanGTA** [comment]
[https://i.loli.net/2018/10/15/5bc387e523714.jpeg](url)

**Comment by BeanGTA** [comment]
Strangled up to heaven, hate life invincible.........
